### PR TITLE
fix: snapshot cluster role name conflict with azuredisk

### PR DESCRIPTION
**Pull request by cyril-corbon**
**What type of PR is this?**

/kind bug
/kind cleanup

**What this PR does / why we need it**:
The clusterrole name is conflicting if we install azuredisk and azurefile with snapshot csi enable

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
that's intentional that azuredisk & file share the same snapshot role, you only need to install snapshot in one driver.

**Comment by cyril-corbon** [comment]
is it written in the documentation I didn't found it ?

**Comment by andyzhangx** [comment]
> is it written in the documentation I didn't find it ?

could you not install snapshot in this azure file driver, and then try snapshot feature?

**Comment by cyril-corbon** [comment]
yes surely :smiley:

**Comment by cyril-corbon** [comment]
So I enable the snapshot controller in the azuredisk chart (the chart version is : v1.5.0) 
I create the following resources:
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
deletionPolicy: Delete
driver: file.csi.azure.com
kind: VolumeSnapshotClass
metadata:
  name: csi-azurefile-vsc
```

```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot-azurefile
  namespace: default
spec:
  volumeSnapshotClassName: csi-azurefile-vsc
  source:
    persistentVolumeClaimName: azurefile-pvc
status:
  boundVolumeSnapshotContentName: snapcontent-d2a6af79-cc74-4f6f-9197-9515a5d91ab6
  readyToUse: false
```

I get these logs : 
```
csi-snapshot-controller-545b848499-6cvsp csi-snapshot-controller I0811 09:43:56.244145       1 snapshot_controller.go:590] createSnapshotContent: Creating content for snapshot default/test-snapshot-azurefile through the plugin ...
csi-snapshot-controller-545b848499-6cvsp csi-snapshot-controller I0811 09:43:56.275103       1 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshot", Namespace:"default", Name:"test-snapshot-azurefile", UID:"d2a6af79-cc74-4f6f-9197-9515a5d91ab6", APIVersion:"snapshot.storage.k8s.io/v1beta1", ResourceVersion:"84771", FieldPath:""}): type: 'Normal' reason: 'CreatingSnapshot' Waiting for a snapshot default/test-snapshot-azurefile to be created by the CSI driver.
csi-snapshot-controller-545b848499-6cvsp csi-snapshot-controller I0811 09:43:56.305384       1 snapshot_controller.go:878] Keeping PVC default/azurefile-pvc, it is used by snapshot default/test-snapshot-azurefile
```
and the volumesnapshot does not become ready

otherwise the volume snapshot work well with azure-disk

**Comment by cyril-corbon** [comment]
I also get the following event : 
```
23s         Warning   SnapshotCreationFailed   volumesnapshotcontent                    Failed to create snapshot: failed to take snapshot of the volume, my-azure-rg##pvc-7c24c865-4587-4336-abb6-6d9e8873b055#: %!q(<nil>)
3m11s       Normal    CreatingSnapshot         volumesnapshot/test-snapshot-azurefile   Waiting for a snapshot default/test-snapshot-azurefile to be created by the CSI driver.
```

**Comment by cyril-corbon** [comment]
the error is from our configuration I think ( because it's not working even if I enable the snapshot in the azurefile chart and disable it from azuredisk)
I will close this pr and I will open an other issue if I still have the problem
Thanks for your help :)

**Comment by andyzhangx** [comment]
follow this guide to provide `csi-snapshotter` logs: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/csi-debug.md#case1-volume-createdelete-issue

**Pull request closed without merging**
