### PR TITLE
test: fix windows e2e test failure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
fix windows e2e test failure, this is just a workaround since `mcr.microsoft.com/dotnet/framework/samples:aspnetapp` is 1.9GB, too large

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
there is nil point issue in `TestSetAzureCredentials` func @ZeroMagic :
```
=== RUN   TestSetAzureCredentials
W0423 02:12:57.949993    8855 utils.go:81] could not create secret: kubeClient is nil
--- PASS: TestSetAzureCredentials (0.10s)
PASS
E0423 02:12:57.952620    8855 runtime.go:76] Observed a panic: Log in goroutine after TestSetAzureCredentials has completed
goroutine 108 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2159660, 0xc000160a50)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/runtime/runtime.go:74 +0xc4
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/runtime/runtime.go:48 +0xbe
panic(0x2159660, 0xc000160a50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
testing.(*common).logDepth(0xc0002e2100, 0xc0003200c0, 0x3b, 0x3)
	/usr/local/go/src/testing/testing.go:678 +0x57a
testing.(*common).log(...)
	/usr/local/go/src/testing/testing.go:658
testing.(*common).Logf(0xc0002e2100, 0x24284ed, 0x13, 0xc000100c70, 0x2, 0x2)
	/usr/local/go/src/testing/testing.go:693 +0x90
sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.TestSetAzureCredentials.func1(0x23fc0c0, 0xc0000f0b40)
	/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefile/utils_test.go:106 +0x159
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/home/prow/go/pkg/mod/k8s.io/client-go@v0.18.1/tools/cache/controller.go:218
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/home/prow/go/pkg/mod/k8s.io/client-go@v0.18.1/tools/cache/shared_informer.go:744 +0x3ae
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00002b738)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:155 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000100f38, 0x2732a00, 0xc00013a0f0, 0xc00011e001, 0xc0000ce000)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:156 +0xb4
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00002b738, 0x3b9aca00, 0x0, 0x1, 0xc0000ce000)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:133 +0x146
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0000fa000)
	/home/prow/go/pkg/mod/k8s.io/client-go@v0.18.1/tools/cache/shared_informer.go:738 +0xa3
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0000ec060, 0xc00008ee60)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:73 +0x6b
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:71 +0x70
panic: Log in goroutine after TestSetAzureCredentials has completed [recovered]
	panic: Log in goroutine after TestSetAzureCredentials has completed

goroutine 108 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/runtime/runtime.go:55 +0x169
panic(0x2159660, 0xc000160a50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
testing.(*common).logDepth(0xc0002e2100, 0xc0003200c0, 0x3b, 0x3)
	/usr/local/go/src/testing/testing.go:678 +0x57a
testing.(*common).log(...)
	/usr/local/go/src/testing/testing.go:658
testing.(*common).Logf(0xc0002e2100, 0x24284ed, 0x13, 0xc000100c70, 0x2, 0x2)
	/usr/local/go/src/testing/testing.go:693 +0x90
sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.TestSetAzureCredentials.func1(0x23fc0c0, 0xc0000f0b40)
	/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefile/utils_test.go:106 +0x159
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/home/prow/go/pkg/mod/k8s.io/client-go@v0.18.1/tools/cache/controller.go:218
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/home/prow/go/pkg/mod/k8s.io/client-go@v0.18.1/tools/cache/shared_informer.go:744 +0x3ae
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00002b738)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:155 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0001e9f38, 0x2732a00, 0xc00013a0f0, 0xc00011e001, 0xc0000ce000)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:156 +0xb4
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00002b738, 0x3b9aca00, 0x0, 0x1, 0xc0000ce000)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:133 +0x146
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0000fa000)
	/home/prow/go/pkg/mod/k8s.io/client-go@v0.18.1/tools/cache/shared_informer.go:738 +0xa3
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0000ec060, 0xc00008ee60)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:73 +0x6b
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:71 +0x70
FAIL	sigs.k8s.io/azurefile-csi-driver/pkg/azurefile	2.361s
?   	sigs.k8s.io/azurefile-csi-driver/pkg/azurefileplugin	[no test files]
```

**Comment by ZeroMagic** [comment]
I have fixed the bug in `TestSetAzureCredentials` func. Ref: #249

**Pull request merged**
