### PR TITLE
feat: add driver userAgent in ARM request

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
feat: add driver userAgent in ARM request

 - original userAgent: `Go/go1.14.2 (amd64-linux) go-autorest/v14.2.1; kubernetes-cloudprovider/v0.0.0-master+$Format:%h$`
 - current userAgent: `file.csi.azure.com/e2e-db5fe240b5e8eebc52b1806bd33651f20ad41caf  gc/go1.16.6 (amd64-linux) db5fe240b5e8eebc52b1806bd33651f20ad41caf/2021-08-09T10:18:40Z`

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
feat: add driver userAgent in ARM request
```

### CODE REVIEW

**Comment by feiskyer** [comment]
For an official released image, would the release tag (instead of commit id) included in the user agent?

**Comment by andyzhangx** [comment]
> For an official released image, would the release tag (instead of commit id) included in the user agent?

for official released image, e.g. `v1.6.0`, it should be like this:
`file.csi.azure.com/v1.6.0 gc/go1.16.6 (amd64-linux) db5fe240b5e8eebc52b1806bd33651f20ad41caf/2021-08-09T10:18:40Z`

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
