### PR TITLE
Tests: Add unit test and run tests with root privileges

### PR DESCRIPTION
**Pull request by animeshk08**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

 /kind test
**What this PR does / why we need it**:
Improves test coverage
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
The unit test now requires root privileges to run.
This is necessary as some operation like mounting need root priviledge

**Release note**:
```
Tests: Add unit tests for node server
Tests: Run unit tests with root priviledges
Tests: Add tests for node server
```

### CODE REVIEW

**Comment by animeshk08** [comment]
Partially fixes the issue: #258

**Comment by andyzhangx** [comment]
@chewong some unit tests needs root permission, do you know where should we put `sudo`, should it be in test-infra repo, this PR tried `sudo go test -v ...`, it failed. thanks.
```
Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
+ make verify
sudo go test -v -race ./pkg/... ./test/utils/credentials
make: sudo: Command not found
make: *** [Makefile:54: unit-test] Error 127
+ EXIT_VALUE=2
+ set +o xtrace
```

**Comment by chewong** [comment]
> @chewong some unit tests needs root permission, do you know where should we put `sudo`, should it be in test-infra repo, this PR tried `sudo go test -v ...`, it failed. thanks.
> 
> ```
> Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
> + make verify
> sudo go test -v -race ./pkg/... ./test/utils/credentials
> make: sudo: Command not found
> make: *** [Makefile:54: unit-test] Error 127
> + EXIT_VALUE=2
> + set +o xtrace
> ```

Opened https://github.com/kubernetes/test-infra/pull/17685, which might fix the issue. I don't think sudo is available in the test container. Could you try removing it?

**Comment by andyzhangx** [comment]
@animeshk08 could you remove `sudo`, and try again? thanks.

**Comment by animeshk08** [comment]
Thanks @andyzhangx `make` works now. Let me fix the errors then we are good to go with this PR :)

**Comment by andyzhangx** [comment]
@animeshk08 can you squash commits next time, e.g.
```
git rebase -i HEAD~5
```

**Comment by andyzhangx** [comment]
the error is different now:
```
=== RUN   TestNodePublishVolume
E0523 23:59:13.572690    8852 nodeserver.go:302] MakeDir failed on target: ./azure.go (mkdir ./azure.go: not a directory)
--- FAIL: TestNodePublishVolume (0.05s)
    nodeserver_test.go:147: 
        	Error Trace:	nodeserver_test.go:147
        	Error:      	Received unexpected error:
        	            	invalid argument
        	Test:       	TestNodePublishVolume
=== RUN   TestNodeUnpublishVolume
E0523 23:59:13.612379    8852 mount_linux.go:150] Mount failed: exit status 32
```

**Comment by animeshk08** [comment]
Thank you for the help @andyzhangx. The build is passing now :rocket:  I have updated Github actions to run with `sudo` as well.

The new coverage is:  
Coverage increased (+12.4%) to 48.826%

**Pull request merged**
