### PR TITLE
test: Improve UTs for nodeserver

### PR DESCRIPTION
**Pull request by animeshk08**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

 /kind test
**What this PR does / why we need it**:
Improves the unit tests for azurefile/nodeserver. Now, root privileges are not required to run the UTs.
This is achieved by creating a new file fake_mounter where the methods of FakeMounter are overridden
**Which issue(s) this PR fixes**:.

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
test: Improve nodeserver unit tests
ci: Remove root privileges to run unit test
```

### CODE REVIEW

**Comment by animeshk08** [comment]
Partially fixes: #258

**Comment by andyzhangx** [comment]
cc @Sakuralbj

**Comment by andyzhangx** [comment]
@animeshk08 could you also spend some time improving smb cifs driver ut coverage? thanks.

**Comment by animeshk08** [comment]
Yes. Was waiting to figure this out. I did not want to carry forward this root privilege issue to other repositories.

**Pull request merged**
