### PR TITLE
chore: fix missing securityContext on controller pods

### PR DESCRIPTION
**Pull request by xrstf**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In #1210 security contexts were added, but none was added to the snapshot controller and the CSI controller. Something similar happened in the azuredisk CSI repo, with the same oversight. In the azuredisk repo, the oversight was fixed in https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1805 and this PR is the equivalent for the azurefile CSI.

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Release note**:
```
Add securityContext to driver controller and snapshot controller Pods.
```

### CODE REVIEW

**Comment by xrstf** [comment]
Did I accidentally actually break something?

**Comment by andyzhangx** [comment]
> Did I accidentally actually break something?

@xrstf No, we are in the middle of migrating all GCP based tests to AWS, that would require efforts.

**Pull request merged**
