### PR TITLE
Enable golint check in golangci-lint

### PR DESCRIPTION
**Pull request by Masquerade0097**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:
Enable golint flag in golangci-lint check. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by chewong** [comment]
To resolve the e2e test failure, could you help move content in `init()` to the beginning of `BeforeSuite` and delete `init()` in https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/test/e2e/suite_test.go? The error is due to the test image upgrading go version to v1.13.4. Thanks.

**Comment by Masquerade0097** [comment]
@chewong Thanks for pointing it out. I have made the changes. Also, can you please point out why pull-azurefile-csi-driver-verify test is failing ?

**Comment by chewong** [comment]
@Masquerade0097 Try running `make verify` and commit any changes in the vendor folder to this branch. I am using Go version 1.13.4.

**Comment by Masquerade0097** [comment]
@andyzhangx @chewong I have made the changes. The `verify` test is now failing due to lint errors which are solved in PR #125. So after this PR and the PR #125 is merged, the test should pass. Please review.

**Comment by chewong** [comment]
verify and e2e job failure should be resolved once https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/128 is merged. @andyzhangx could you take another look at https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/128?

**Pull request merged**
