### PR TITLE
test: Add tests for azurefile and controllerserver

### PR DESCRIPTION
**Pull request by animeshk08**
This commit also add some nit suggestions to server
and server_test.

Signed-off-by: Animesh Kumar <animuz111@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind test
**What this PR does / why we need it**:
Adds unit tests
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
test: Add tests for azurefile and controllerserver
```

### CODE REVIEW

**Comment by animeshk08** [comment]
Partially fixes: #258

**Comment by animeshk08** [comment]
An increase in the runtime of unit tests(~15secs) may be noticed as the following lines are also covered now: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L138

**Comment by animeshk08** [comment]
A few of the methods were not covered in this PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/298. Thus the unit test remains partial for them. e.g,
* https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L605
* https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L485
* https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L411

and others which primarily make calls to https://github.com/Azure/azure-storage-file-go/blob/master/azfile/url_file.go

\cc @andyzhangx @ZeroMagic

**Comment by animeshk08** [comment]
Also, coverage is now ~80% yayy! :rocket:

**Comment by andyzhangx** [comment]
cc @Sakuralbj

**Comment by andyzhangx** [comment]
> A few of the methods were not covered in this PR: #298. Thus the unit test remains partial for them. e.g,
> 
> * https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L605
> * https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L485
> * https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L411
> 
> and others which primarily make calls to https://github.com/Azure/azure-storage-file-go/blob/master/azfile/url_file.go
> 
> \cc @andyzhangx @ZeroMagic

@animeshk08 thanks, are you going to open a new issue? thanks.

**Pull request merged**
