### PR TITLE
fix: expose GET_VOLUME_STATS

### LINKED ISSUE #334: Add GET_VOLUME_STATS Capability to NodeService Capability
**What happened**:
Kubelet is not exposing volume stats even though it is implemented through #306 

**What you expected to happen**:
Expose volume stats through kubelet metric

**How to reproduce it**:
Create PVC and check for metric in kubelet metric endpoint

**Anything else we need to know?**:
```csi.NodeServiceCapability_RPC_GET_VOLUME_STATS``` should be added to node service capability so kubelet can retrieve metrics.
Not really sure if this was blocked to wait for the next release.

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/26d02c5f2f29e0237047f4c384493b9a98b7083b/pkg/azurefile/azurefile.go#L170-L172

**Environment**:
- CSI Driver version: master-branch
- Kubernetes version (use `kubectl version`): 1.17.3

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Expose volume stats through kubelet metric

**Which issue(s) this PR fixes**:

Fixes #334

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
cc @onesolpark

**Release note**:
```
none
```

### CODE REVIEW

**Comment by onesolpark** [comment]
@andyzhangx Thank you very much appreciate it.

**Comment by andyzhangx** [comment]
@Sakuralbj 
could you fix the sanity test failure with this PR:
```
• Failure [0.016 seconds]
Node Service
/home/prow/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/tests.go:44
  NodeGetVolumeStats
  /home/prow/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/node.go:408
    should fail when volume is not found [It]
skipped 88 lines unfold_more
I0709 09:31:15.318987    8586 utils.go:112] GRPC request: volume_id:"azurefile-csi-driver-test-b7e80437-c1c6-11ea-b9fd-baae8628d029#fb7e49a87580a478d82fa2d#sanity-node-get-volume-stats-29435036-0aacbe09#" 
I0709 09:31:15.318998    8586 controllerserver.go:224] DeleteVolume called with request {azurefile-csi-driver-test-b7e80437-c1c6-11ea-b9fd-baae8628d029#fb7e49a87580a478d82fa2d#sanity-node-get-volume-stats-29435036-0aacbe09# map[] {} [] 0}
I0709 09:31:15.459172    8586 controllerserver.go:244] azure file(sanity-node-get-volume-stats-29435036-0aacbe09) under rg(azurefile-csi-driver-test-b7e80437-c1c6-11ea-b9fd-baae8628d029) account(fb7e49a87580a478d82fa2d) volume(azurefile-csi-driver-test-b7e80437-c1c6-11ea-b9fd-baae8628d029#fb7e49a87580a478d82fa2d#sanity-node-get-volume-stats-29435036-0aacbe09#) is deleted successfully
I0709 09:31:15.459220    8586 utils.go:118] GRPC response: 
• Failure [9.671 seconds]
Node Service
/home/prow/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/tests.go:44
  NodeGetVolumeStats
  /home/prow/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/node.go:408
    should fail when volume does not exist on the specified path [It]
skipped 1231 lines unfold_more
[Fail] Node Service NodeGetVolumeStats [It] should fail when volume does not exist on the specified path 
/home/prow/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/node.go:585
Ran 53 of 72 Specs in 78.646 seconds
FAIL! -- 51 Passed | 2 Failed | 0 Pending | 19 Skipped
--- FAIL: TestSanity (78.68s)
```

**Comment by andyzhangx** [comment]
close this PR, would be addressed in https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/338

**Pull request closed without merging**
