### PR TITLE
test: Add unit tests

### PR DESCRIPTION
**Pull request by animeshk08**
This commit adds unit tests for unimplemented methods.
The commit also adds minor unit tests for azurefile and
azurefile/utils.
The imported dependencies are also sorted.

Signed-off-by: Animesh Kumar <animuz111@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by animeshk08** [comment]
Partially fixes: #258
This PR is primarily aimed to cover the unimplemented methods. These unit test can be changed in the future if these methods are implemented.
A considerable increase is achieved in code coverage:  `Coverage increased (+3.07%) to 82.922% `

**Comment by andyzhangx** [comment]
cc @Sakuralbj

**Pull request merged**
