### PR TITLE
Tests: Add Controller server tests

### PR DESCRIPTION
**Pull request by animeshk08**
Signed-off-by: Animesh Kumar <animuz111@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation

> /kind failing-test
> /kind feature
> /kind flake

/kind test

**What this PR does / why we need it**:
Improves test coverage
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Tests: Add Controller server tests
```

### CODE REVIEW

**Comment by animeshk08** [comment]
Partially fixes issue: #258

**Comment by animeshk08** [comment]
Sorry for the delay! PR is ready for review @andyzhangx

**Comment by andyzhangx** [comment]
> Partially fixes issue: #258

@animeshk08 thanks, can you also file an issue to tracking this issue.

**Pull request merged**
