### PR TITLE
update base image to bullseye

### PR DESCRIPTION
**Pull request by sozercan**
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Update base image to debian bullseye which should fix the installation issue with nfs-common

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
```console
# docker images | grep debian-base
k8s.gcr.io/build-image/debian-base                         bullseye-v1.0.0    316d9421ac48   7 days ago      62.7MB
k8s.gcr.io/build-image/debian-base-arm64                   buster-v1.6.0      88e0bf68d41c   4 months ago    60.1MB
k8s.gcr.io/build-image/debian-base-amd64                   buster-v1.6.0      a064b44e3aa7   4 months ago    60.8MB
k8s.gcr.io/build-image/debian-base                         buster-v1.6.0      a064b44e3aa7   4 months ago    60.8MB
```

**Release note**:
```
Update Linux base image to k8s.gcr.io/build-image/debian-base:bullseye-v1.0.0
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by sozercan** [comment]
@andyzhangx do you know why tests are failing?

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
