### PR TITLE
chore: change volumeid format to include diskname

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
chore: change volumeid format to include diskname

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
> Hello @andyzhangx
> 
> hope you are doing well. After installing the last version of the csi, we had to recreate all the PVCs. In fact, our pods were not able to mount the volumes anymore because of this issue:
> `getAccountInfo(***#**#a***) failed with error: error parsing volume id: "rg-bru-sh-aks-dev-tst-001#stabrugv2stdaksdevtst001#aks-tst-wso2am-car", should at least contain three #`
> 
> hopefully we are not in production yet. I think one should make sure that these kind of changes are backward compatible. what's the purpose of this change bu the way?
> 
> thanks a lot

thanks, I have worked out a PR to fix that issue: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/214, pls use version `v0.4.0` now, it won't have volumeid compatibility issue. Thanks.

**Comment by aelmanaa** [comment]
Hello @andyzhangx 

well I installed the latest version ( I guess v0.5) and we recreated all the PVC, now it seem to work. I don't want to rollback now.
by the way, I'm looking all the installation file here 
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-master.md
https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.4.0/deploy/csi-azurefile-controller.yaml

in all versions, you don't mention a specific versions for azurefile-csi. you always pick latest tag. It would be better to specify the tag, don't you think so? 

mcr.microsoft.com/k8s/csi/azurefile-csi:latest



kr

**Comment by andyzhangx** [comment]
for installing a specific version, you should following such guide, e.g. to install v0.5.0, you could follow: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-v0.5.0.md
now all versions from v0.4.0, v0.5.0 or master branch version all won't have the compatibility issue.

in brief, you could install a specific version like following:
```
curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/install-driver-standalone.sh | bash -s v0.5.0 --
```

**Comment by andyzhangx** [comment]
and you could find  installation guide of every version here: https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/docs

**Pull request merged**
