### PR TITLE
feat: switch snapshot CRDs from alpha to beta

### LINKED ISSUE #347: VolumeSnapshot never reaches ReadyToUse state
**What happened**:
A VolumeSnapshot of a PVC with a StorageClass using the azurefile-csi-driver is not successful; the VolumeSnapshot stays in ReadyToUse state: <nil> forever

**What you expected to happen**:

The VolumeSnapshot is being created and goes into Ready To Use state at some point

**How to reproduce it**:

- have a basically new AKS 1.17.7 cluster
- install the VolumeSnaphsot CRDs, following the Kubernets 1.17 blog post: https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/
- install the master branch version of this azurefile-csi-driver (tried 0.7 before, too)
- create a storage class according to the example listed in the README.md
- deploy a ReadWriteMany PVC using that storage class (identical to example, only size and name changed)
- Create a VolumeSnapshot of that PVC (again, from example, only names and namespaces changed)

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: master 
- Kubernetes version (use `kubectl version`): 1.17.7 AKS / 1.18.3 kubectl
- Others:
I installed the disk driver, too (0.7 version) and was able to create a snapshot of a volume based on the disk driver

### PR DESCRIPTION
**Pull request by ZeroMagic**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
switch snapshot CRDs from alpha to beta

**Which issue(s) this PR fixes**:

Fixes #347

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
would you also enable snapshot e2e test later?

**Comment by ZeroMagic** [comment]
> would you also enable snapshot e2e test later?

ok. I will add it in this PR soon.

**Comment by andyzhangx** [comment]
we now have snapshot-controller in both azure disk and azure file CSI drivers, need to check whether there is conflict when install these two drivers together by both helm and yaml installation.

**Pull request merged**
