### PR TITLE
Tests:Improve Unit Tests for driver and identityserver

### PR DESCRIPTION
**Pull request by animeshk08**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

 /kind test
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Add unit tests for driver and identity server
```

### CODE REVIEW

**Comment by animeshk08** [comment]
Partial fix for the issue: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/258

**Comment by andyzhangx** [comment]
@animeshk08 thanks for the contribution.
pls run `hack/update-gofmt.sh` thanks.

**Comment by animeshk08** [comment]
Sorry @andyzhangx I have updated the PR. I am working on  improving other tests now :)

**Comment by andyzhangx** [comment]
> Sorry @andyzhangx I have updated the PR. I am working on improving other tests now :)

good progress! 
coverage/coveralls — Coverage increased (+3.6%) to 25.417%

**Pull request merged**
