### PR TITLE
[release-1.28] feat: support volume cloning

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
feat: support volume cloning

cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1278

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
feat: support volume cloning
```

### CODE REVIEW

**Comment by link-webcreations** [comment]
Hello,

Thanks for this !
Just a note, when we use AzureFile with NFS: `protocol nfs is not supported for volume cloning`

**Comment by andyzhangx** [comment]
> Hello,
> 
> Thanks for this ! Just a note, when we use AzureFile with NFS: `protocol nfs is not supported for volume cloning`

@link-webcreations thanks, I have worked out a doc PR to address this question: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1631, and yes, nfs file share is not supported for volume cloning.

**Pull request merged**
