### PR TITLE
feat: use file metadata for vhd disk lock

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR enables `ControllerPublishVolume` and `ControllerUnpublishVolume`, and use file metadata for vhd disk lock.

Ideally we should use [lease](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-file) to lock to prevent race condition, while that API may be not ready yet, so we use metadata for locking first.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
feat: use file metadata for vhd disk lock
```

/hold
hold for testing first

### CODE REVIEW

**Comment by andyzhangx** [comment]
hi @chewong did you hit this delete resource group timeout issue before?

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azurefile-csi-driver/193/pull-azurefile-csi-driver-sanity/1237027955788484614/build-log.txt

```
2020/03/09 14:55:26 Deleting resource group azurefile-csi-driver-test-a59c174a-6215-11ea-9bf6-4e5f9aa97dbc
panic: test timed out after 10m0s

goroutine 53 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000132200, 0x99a955, 0xa, 0x9bea60, 0x4890f6)
	/usr/local/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc000132100)
	/usr/local/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc000132100, 0xc000143dc0)
	/usr/local/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc0000d6600, 0xda5240, 0x1, 0x1, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc000130180, 0x0)
	/usr/local/go/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:44 +0x135

goroutine 20 [select]:
github.com/Azure/go-autorest/autorest.DelayForBackoffWithCap(0x37e11d600, 0x0, 0x0, 0xc0000ae240, 0xc00015e580)
	/home/prow/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.0/sender.go:405 +0x14a
github.com/Azure/go-autorest/autorest.DelayForBackoff(...)
	/home/prow/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.0/sender.go:391
github.com/Azure/go-autorest/autorest/azure.(*Future).WaitForCompletionRef(0xc00018fb30, 0xa52ec0, 0xc0000c6010, 0xa48820, 0xc0000b9cd0, 0xa48b40, 0xc00016e840, 0x0, 0x0, 0xdf8475800, ...)
	/home/prow/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.0/azure/async.go:196 +0x333
sigs.k8s.io/azurefile-csi-driver/test/utils/azure.(*Client).DeleteResourceGroup(0xc000174000, 0xa52ec0, 0xc0000c6010, 0xc000118100, 0x3e, 0x28, 0xc000092900)
	/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/utils/azure/azure_helpers.go:97 +0x369
sigs.k8s.io/azurefile-csi-driver/test/sanity.TestSanity.func2(0xc000145880, 0xc000174000, 0xa52ec0, 0xc0000c6010, 0xc000132200)
	/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/sanity/sanity_test.go:61 +0xe7
sigs.k8s.io/azurefile-csi-driver/test/sanity.TestSanity(0xc000132200)
	/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/sanity/sanity_test.go:90 +0x7ca
testing.tRunner(0xc000132200, 0x9bea60)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
```

**Comment by chewong** [comment]
No I haven't. Let's try re-testing it again.
/retest

**Comment by andyzhangx** [comment]
Looks like I need to upgrade go-autorest to a higher version:
https://github.com/Azure/go-autorest/issues/357

**Pull request merged**
