### PR TITLE
fix: create nonroot user in Dockerfile

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: create nonroot user in Dockerfile

related to issue: https://github.com/Azure/aad-pod-identity/issues/805

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
fix: create nonroot user in Dockerfile
```

### CODE REVIEW

**Review by ZeroMagic — APPROVED** [review]
/lgtm

**Comment by andyzhangx** [comment]
driver could not start up running with nonroot user:
```
I0923 02:37:11.825836       1 azure.go:50] reading cloud config from secret
W0923 02:37:12.106489       1 azure_config.go:52] Failed to get cloud-config from secret: failed to get secret azure-cloud-provider: secrets "azure-cloud-provider" not found, skip initializing from secret
I0923 02:37:12.106521       1 azure.go:56] could not read cloud config from secret
I0923 02:37:12.106530       1 azure.go:66] use default AZURE_CREDENTIAL_FILE env var: /etc/kubernetes/azure.json
E0923 02:37:12.106560       1 azure.go:71] Failed to load config from file: /etc/kubernetes/azure.json
F0923 02:37:12.106708       1 azurefile.go:144] failed to get Azure Cloud Provider, error: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc0000b0001, 0xc000118000, 0xbb, 0x1da)
	/home/prow/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2647520, 0xc000000003, 0x0, 0x0, 0xc0003b2ee0, 0x259adee, 0xc, 0x90, 0x0)
	/home/prow/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x2647520, 0x3, 0x0, 0x0, 0x19d66b0, 0x2d, 0xc00019be40, 0x1, 0x1)
	/home/prow/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
	/home/prow/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1456
sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.(*Driver).Run(0xc0003a0000, 0x7ffd1e486a87, 0x14, 0x0, 0x0, 0xc00000c300)
	/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefile/azurefile.go:144 +0x253
main.handle()
	/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefileplugin/main.go:70 +0x12f
main.main()
	/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefileplugin/main.go:61 +0xae
```

**Comment by chewong** [comment]
Mounted files like azure.json can only be read by root. To work around this issue, we added 
```
securityContext:
   runAsUser: 0
```
to our containers.

**Comment by andyzhangx** [comment]
> Mounted files like azure.json can only be read by root. To work around this issue, we added
> 
> ```
> securityContext:
>    runAsUser: 0
> ```
> 
> to our containers.

@chewong thanks, that looks like a trick, we do not allow non-root user inside image, while finally run the container as root user.

**Pull request merged**
