### PR TITLE
doc: change image repo address

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
doc: change image repo address

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
doc: change image repo address
```

### CODE REVIEW

**Comment by ZeroMagic** [comment]
The "NotFound" error is solved in another PR(https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/393). 
```
func (t *TestPersistentVolumeClaim) removeFinalizers() {
        pv, err := t.client.CoreV1().PersistentVolumes().Get(context.TODO(), t.persistentVolume.Name, metav1.GetOptions{})	
        if err != nil && strings.Contains(err.Error(), "not found") {
		return
	}
...
```

Here could rerun the test to pass.

**Comment by chewong** [comment]
Do we need to backfill for < v0.6.0?

**Comment by andyzhangx** [comment]
> Do we need to backfill for < v0.6.0?

I don't think so, I will only change the image repo address from v0.9.0 in this repo deployment

**Pull request merged**
