### PR TITLE
feat: add grpc interceptor to azurefile driver

### PR DESCRIPTION
**Pull request by steeling**
Add basic grpc metrics to the CSI Driver

/kind feature

**What this PR does / why we need it**:

More metrics for deeper insights into performance of the driver

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by andyzhangx** [comment]
thanks, could you fix the `pull-azurefile-csi-driver-verify` error?

**Comment by steeling** [comment]
> thanks, could you fix the `pull-azurefile-csi-driver-verify` error?

fixed, although still a couple jobs failing. Do you know if those are transient issues?

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
