### PR TITLE
go lint failures

### PR DESCRIPTION
**Pull request by LenardLee**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
fix go lint failures

### CODE REVIEW

**Comment by andyzhangx** [comment]
hi @LenardLee thanks for the contribution.
I have one question, how did you catch this golint issue? it looks like original the https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/hack/verify-golint.sh does not verify golint issue completely.
could you also fix that in this PR? thanks.

**Comment by andyzhangx** [comment]
@Masquerade0097 could you help improve lint test? Thanks.

**Comment by Masquerade0097** [comment]
@andyzhangx I have made a PR #128 which enables the golint check in golangci-lint. This points the following lint errors - 

```
	fileUrlTemplate  = "https://%s.file.%s"
	^
pkg/azurefile/controllerserver.go:340:18: method getShareUrl should be getShareURL (golint)
func (d *Driver) getShareUrl(sourceVolumeID string) (azfile.ShareURL, error) {
                 ^
pkg/azurefile/controllerserver.go:406:11: if block ends with a return statement, so drop this else and outdent its block (golint)
			} else {
			       ^
test/e2e/dynamic_provisioning.go:25:2: should not use dot imports (golint)
	. "github.com/onsi/ginkgo"
	^
test/e2e/pre_provisioning.go:25:2: should not use dot imports (golint)
	. "github.com/onsi/ginkgo"
	^
test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go:22:2: should not use dot imports (golint)
	. "github.com/onsi/ginkgo"
	^
test/utils/azure/azure_helpers.go:14:6: type name will be used as azure.AzureClient by other packages, and that stutters; consider calling this Client (golint)
type AzureClient struct {
     ^
test/utils/credentials/credentials.go:35:2: const tenantIdEnvVar should be tenantIDEnvVar (golint)
	tenantIdEnvVar        = "TENANT_ID"
	^
test/utils/credentials/credentials.go:36:2: const subscriptionIdEnvVar should be subscriptionIDEnvVar (golint)
	subscriptionIdEnvVar  = "SUBSCRIPTION_ID"
	^
test/utils/credentials/credentials.go:37:2: const aadClientIdEnvVar should be aadClientIDEnvVar (golint)
	aadClientIdEnvVar     = "AAD_CLIENT_ID"
	^
test/utils/credentials/credentials.go:42:2: const tenantIdChinaEnvVar should be tenantIDChinaEnvVar (golint)
	tenantIdChinaEnvVar        = "TENANT_ID_CHINA"
	^
test/utils/credentials/credentials.go:43:2: const subscriptionIdChinaEnvVar should be subscriptionIDChinaEnvVar (golint)
	subscriptionIdChinaEnvVar  = "SUBSCRIPTION_ID_CHINA"
	^
test/utils/credentials/credentials.go:44:2: const aadClientIdChinaEnvVar should be aadClientIDChinaEnvVar (golint)
	aadClientIdChinaEnvVar     = "AAD_CLIENT_ID_CHINA"
	^
test/utils/credentials/credentials.go:52:6: type name will be used as credentials.CredentialsConfig by other packages, and that stutters; consider calling this Config (golint)
type CredentialsConfig struct {
     ^
test/utils/credentials/credentials.go:58:6: type name will be used as credentials.CredentialsFromProw by other packages, and that stutters; consider calling this FromProw (golint)
type CredentialsFromProw struct {
     ^
test/utils/credentials/credentials.go:82:13: var tenantId should be tenantID (golint)
	var cloud, tenantId, subscriptionId, aadClientId, aadClientSecret, resourceGroup, location string
	           ^
test/utils/credentials/credentials.go:161:37: func parameter tenantId should be tenantID (golint)
func parseAndExecuteTemplate(cloud, tenantId, subscriptionId, aadClientId, aadClientSecret, resourceGroup, location string) (*Credentials, error) {
                                    ^
```

Will these failures be fixed in this PR or should I fix them in my PR ?

**Comment by andyzhangx** [comment]
@Masquerade0097 pls fix it in the same PR when enabling golint check, you may also skip golint test in our tests.

**Comment by andyzhangx** [comment]
/hold
looks like there is sth. wrong with the original code, need to fix

**Pull request merged**
