### PR TITLE
chore: upgrade csi-attacher version to v3.0.2

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
chore: upgrade csi-attacher version to v3.0.2 (for csi migration dependency)
`mcr.microsoft.com/oss/kubernetes-csi/csi-attacher:v3.0.2` has the fix already: https://github.com/kubernetes/kubernetes/pull/94904

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
csi-attacher v3.0.0 does not work well on k8s 1.15.12, need to get the least supported k8s version at first.

**Comment by ZeroMagic** [comment]
From the release note https://github.com/kubernetes-csi/external-attacher/releases/tag/v3.0.0 ,  the minimum Kubernetes version is 1.17

**Comment by andyzhangx** [comment]
> From the release note https://github.com/kubernetes-csi/external-attacher/releases/tag/v3.0.0 , the minimum Kubernetes version is 1.17

that's true, while we don't want to make minimum version as 1.17 right now, will try to do hotfix for csi-attacher v2.x to make migration work first.

**Comment by andyzhangx** [comment]
```
Nov  7 07:22:29.349: INFO: At 2020-11-07 07:06:48 +0000 UTC - event for pvc-rhnkx: {file.csi.azure.com_k8s-agentpool1-29483490-0_d0817931-ea0f-48bb-9067-870768068fc0 } Provisioning: External provisioner is provisioning volume for claim "azurefile-631/pvc-rhnkx"
Nov  7 07:22:29.349: INFO: At 2020-11-07 07:06:48 +0000 UTC - event for pvc-rhnkx: {persistentvolume-controller } ExternalProvisioning: waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
Nov  7 07:22:29.349: INFO: At 2020-11-07 07:07:06 +0000 UTC - event for pvc-rhnkx: {file.csi.azure.com_k8s-agentpool1-29483490-0_d0817931-ea0f-48bb-9067-870768068fc0 } ProvisioningSucceeded: Successfully provisioned volume pvc-d848d23d-347e-40f9-a3a9-0b8efa729b88
Nov  7 07:22:29.349: INFO: At 2020-11-07 07:07:08 +0000 UTC - event for azurefile-volume-tester-965tj: {default-scheduler } Scheduled: Successfully assigned azurefile-631/azurefile-volume-tester-965tj to k8s-agentpool1-29483490-0
Nov  7 07:22:29.349: INFO: At 2020-11-07 07:07:08 +0000 UTC - event for azurefile-volume-tester-965tj: {attachdetach-controller } SuccessfulAttachVolume: AttachVolume.Attach succeeded for volume "pvc-d848d23d-347e-40f9-a3a9-0b8efa729b88" 
Nov  7 07:22:29.349: INFO: At 2020-11-07 07:07:24 +0000 UTC - event for azurefile-volume-tester-965tj: {kubelet k8s-agentpool1-29483490-0} FailedMount: MountVolume.MountDevice failed for volume "pvc-d848d23d-347e-40f9-a3a9-0b8efa729b88" : fetching NodeStageSecretRef default/azure-storage-account-f5ffebf7f32ce4953afa073-secret failed: kubernetes.io/csi: failed to find the secret azure-storage-account-f5ffebf7f32ce4953afa073-secret in the namespace default with error: secrets "azure-storage-account-f5ffebf7f32ce4953afa073-secret" is forbidden: User "system:node:k8s-agentpool1-29483490-0" cannot get resource "secrets" in API group "" in the namespace "default": no relationship found between node 'k8s-agentpool1-29483490-0' and this object
```

**Comment by andyzhangx** [comment]
after this PR(https://github.com/kubernetes-csi/external-attacher/pull/293) get merged and new csi-attacher `3.1.1` release is published, we will only support k8s 1.17+

**Pull request closed without merging**
