### PR TITLE
test: enable fsGroup external test for nfs

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
test: enable fsGroup external test for nfs

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by gnufied** [comment]
How does `fsGroup` work for NFS @andyzhangx ? Is kubelet changing the permissions recursively.

**Comment by andyzhangx** [comment]
> How does `fsGroup` work for NFS @andyzhangx ? Is kubelet changing the permissions recursively.

@gnufied yes, for nfs csi driver, it's already supported: https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/test/external-e2e/testdriver.yaml#L13, while for this azure file driver, there is a block issue related to nfs implementation on azure file: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/682

**Pull request merged**
